In [1]:
import cv2
import numpy as np

In [6]:
img = cv2.imread('media/card.png')
cv2.imshow('Original', img)

print(img.shape)

width =400
height = 500

pts1 = np.float32([[225,5],[86,328],[454,104],[316,427]]) #cevirmek istedigimiz noktalar
pts2 = np.float32([[0,0],[0,height],[width,0],[width,height]]) #cevirmek istedigimiz noktalarin gidecegi noktalar

matrix = cv2.getPerspectiveTransform(pts1,pts2) #donusum matrisi
print(matrix)

output= cv2.warpPerspective(img,matrix,(width,height)) #donusum islemi

cv2.imshow('Output', output)


cv2.waitKey(0)
cv2.destroyAllWindows()

(445, 511, 3)
[[ 1.46839362e+00  6.31909328e-01 -3.33548111e+02]
 [-5.65290401e-01  1.30759093e+00  1.20652386e+02]
 [-8.28412111e-06  7.82592983e-06  1.00000000e+00]]
